# run-parameter-study.sub

executable = run-parameter-study.sh
arguments = heat-config-$(Process).yaml

log = run-parameter-study_$(Cluster)_$(Process).log
error = run-parameter-study_$(Cluster)_$(Process).err
output = run-parameter-study_$(Cluster)_$(Process).out

# transfer_input_files = file1,/absolute/pathto/file2,etc

requirements = (OSGVO_OS_STRING == "RHEL 7")
request_cpus = 1
request_memory = 1GB
request_disk = 5GB

queue 10
